# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/add/, role: ROLE_ADMIN }
        - { path: ^/view/, role: ROLE_USER }
        - { path: ^/edit/, role: ROLE_ADMIN }
        - { path: ^/search/, role: ROLE_USER }
        - { path: ^/results/, role: ROLE_USER }
        - { path: ^/editprofile/, role: ROLE_SUPER_ADMIN }
        - { path: ^/addprofile/, role: ROLE_SUPER_ADMIN }
        - { path: ^/users/, role: ROLE_SUPER_ADMIN }
        - { path: ^/collection/, role: ROLE_SUPER_ADMIN }
        - { path: ^/mineral, role: ROLE_SUPER_ADMIN }
        
    access_denied_url: /error