#delete ----------------

app_delete_contributor:
    path:     /delete/contributor/{pk}
    defaults: 
     _controller: AppBundle:Delete:deletecontributor

app_delete_flightplan:
    path:     /delete/flightplan/{pk}
    defaults: 
     _controller: AppBundle:Delete:deleteflightplan 

app_delete_ddocaerphoto:
    path:     /delete/ddocaerphoto/{pk}/{container_pk}
    defaults: 
     _controller: AppBundle:Delete:deleteddocaerphoto     
     
app_delete_contribution:
    path:     /delete/contribution/{pk}
    defaults: 
     _controller: AppBundle:Delete:deletecontribution

app_delete_dkeyword:
    path:     /delete/dkeyword/{pk}/{container_pk}
    defaults: 
     _controller: AppBundle:Delete:deletedkeyword

app_delete_ddoctitle:
    path:     /delete/ddoctitle/{pk}/{container_pk}
    defaults: 
     _controller: AppBundle:Delete:deleteddoctitle

app_delete_dlinkcontdoc:
    path:     /delete/dlinkcontdoc/{pk}/{container_pk}
    defaults: 
     {_controller: AppBundle:Delete:deletedlinkcontdoc}
     
app_delete_dlinkdocloc:
    path:     /delete/dlinkdocloc/{pk}/{container_pk}
    defaults: 
     {_controller: AppBundle:Delete:deletedlinkdocloc}

app_delete_dlinkdoclocfrompoint:
    path:     /delete/dlinkdoclocpt/{pk}/{container_pk}
    defaults: 
     {_controller: AppBundle:Delete:deletedlinkdoclocfrompoint}


app_delete_dlinkcontdoc_from_contrib:
    path:     /delete/dlinkcontdoc_contrib/{pk}/{container_pk}
    defaults: 
     {_controller: AppBundle:Delete:deletedlinkcontribution}
     
app_delete_satellite:
    path:     /delete/ddocsatellite/{pk}/{container_pk}
    defaults: 
     _controller: AppBundle:Delete:deleteddocsatellite
     
app_delete_map:
    path:     /delete/ddocmap/{pk}/{container_pk}
    defaults: 
     _controller: AppBundle:Delete:deleteddocmap

app_delete_archive:
    path:     /delete/ddocarchive/{pk}/{container_pk}
    defaults: 
     _controller: AppBundle:Delete:deleteddocarchive
     
app_delete_scale:
    path:     /delete/ddocscale/{pk}/{container_pk}
    defaults: 
     _controller: AppBundle:Delete:deleteddocscale
     
app_delete_film:
    path:     /delete/ddocfilm/{pk}/{container_pk}
    defaults: 
     _controller: AppBundle:Delete:deleteddocfilm
     
app_delete_stratum_from_point:
    path:     /delete/stratum_from_point/{pk}/{container_pk}
    defaults: 
     _controller: AppBundle:Delete:deletestratum_from_point
     
app_delete_stratum_description:
    path:     /delete/stratum_description/{pk}/{container_pk}
    defaults: 
     _controller: AppBundle:Delete:deletestratum_description
     
app_delete_mineral:
    path:    /delete/mineral/{pk}
    defaults:
     _controller: AppBundle:Delete:delete_mineral
     
app_delete_mineralhierarchy:
    path:    /delete/mineralhierarchy/{pk}
    defaults:
     _controller: AppBundle:Delete:delete_mineralhierarchy

app_delete_mineral_from_sample:
    path:    /delete/mineral_from_sample/{pk}/{container_pk}
    defaults:
     _controller: AppBundle:Delete:delete_mineral_from_sample

app_delete_granulo_from_sample:
    path:    /delete/granulo_from_sample/{pk}/{container_pk}
    defaults:
     _controller: AppBundle:Delete:delete_granulo_from_sample

app_delete_heavymin_from_sample:
    path:    /delete/heavymin_from_sample/{pk}/{container_pk}
    defaults:
     _controller: AppBundle:Delete:delete_heavymin_from_sample

app_delete_aray_from_sample:
    path:    /delete/aray_from_sample/{pk}/{container_pk}
    defaults:
     _controller: AppBundle:Delete:delete_aray_from_sample 

app_delete_slimplate_from_sample:
    path:    /delete/slimplate_from_sample/{pk}/{container_pk}
    defaults:
     _controller: AppBundle:Delete:delete_slimplate_from_sample      

app_delete_locality_from_sample:
    path:    /delete/loc_from_sample/{pk}/{container_pk}
    defaults:
     _controller: AppBundle:Delete:delete_loc_from_sample

app_delete_contrib_from_sample:
    path:    /delete/contrib_from_sample/{pk}/{container_pk}
    defaults:
     _controller: AppBundle:Delete:delete_contrib_from_sample

app_delete_doc_from_sample:
    path:    /delete/doc_from_sample/{pk}/{container_pk}
    defaults:
     _controller: AppBundle:Delete:delete_doc_from_sample        
     
app_delete_sample:
    path:    /delete/dsamplegs/{pk}
    defaults:
     _controller: AppBundle:Delete:delete_sample
     
app_delete_contrib_from_point:
    path:    /delete/contrib_from_point/{pk}/{container_pk}
    defaults:
     _controller: AppBundle:Delete:delete_contrib_from_point
     
