# src/AppBundle/Resources/config/routing.yml
#external
app_main:
    resource: main.yml    

app_autocomplete:
    resource: autocomplete.yml
    
app_widgets:
    resource: widgets.yml
    
app_delete:
    resource: delete.yml
    
