get_widget_keyword:
    path:     /get_widget_keyword
    defaults: 
     _controller: AppBundle:Widget:widget_keyword
    methods:  GET

get_widget_title:
    path:     /get_widget_title
    defaults: 
     _controller: AppBundle:Widget:widget_title
    methods:  GET

get_widget_satellite:
    path:     /get_widget_satellite
    defaults: 
     _controller: AppBundle:Widget:widget_satellite
    methods:  GET
    
get_widget_map:
    path:     /get_widget_map
    defaults: 
     _controller: AppBundle:Widget:widget_map
    methods:  GET
    
get_widget_archive:
    path:     /get_widget_archive
    defaults: 
     _controller: AppBundle:Widget:widget_archive
    methods:  GET
    
get_widget_scale:
    path:     /get_widget_scale
    defaults: 
     _controller: AppBundle:Widget:widget_scale
    methods:  GET
    
get_widget_film:
    path:     /get_widget_film
    defaults: 
     _controller: AppBundle:Widget:widget_film
    methods:  GET

get_widget_doc_to_contrib:
    path:     /get_widget_doc_to_contrib
    defaults: 
     _controller: AppBundle:Widget:widget_doc_to_contrib
    methods:  GET
    
get_widget_doc_to_dloccenter:
    path:     /get_widget_doc_to_dloccenter
    defaults: 
     _controller: AppBundle:Widget:widget_doc_to_dloccenter
    methods:  GET
    
get_widget_contrib_to_doc:
    path:     /get_widget_contrib_to_doc
    defaults: 
     _controller: AppBundle:Widget:widget_contrib_to_doc
    methods:  GET
    
get_widget_point_to_stratum:
    path:     /get_widget_point_to_stratum
    defaults: 
     _controller: AppBundle:Widget:widget_point_to_stratum
    methods:  GET
    
get_widget_point_to_doc:
    path:     /get_widget_point_to_doc
    defaults: 
     _controller: AppBundle:Widget:widget_point_to_doc
    methods:  GET
    
get_widget_point_to_stratum_description:
    path:     /get_widget_point_to_stratum_description
    defaults: 
     _controller: AppBundle:Widget:widget_point_to_stratum_description
    methods:  GET


get_widget_contribdetail:
    path:     /get_widget_contribdetail
    defaults: 
     _controller: AppBundle:Widget:widget_contributordetail
    methods:  GET
    
get_widget_doc_to_flightplan:
    path:     /get_widget_doc_to_flightplan
    defaults: 
     _controller: AppBundle:Widget:widget_doc_to_flightplan
    methods:  GET
    
get_widget_sample_to_mineral:
    path: get_widget_sample_to_mineral
    defaults: 
     _controller: AppBundle:Widget:widget_sample_to_mineral
    methods:  GET
    
get_widget_sample_to_granulo:
    path: get_widget_sample_to_granulo
    defaults: 
     _controller: AppBundle:Widget:widget_sample_to_granulo
    methods:  GET
    
get_widget_sample_to_heavymin:
    path: get_widget_sample_to_heavymin
    defaults: 
     _controller: AppBundle:Widget:widget_sample_to_heavymin
    methods:  GET
    
get_widget_sample_to_aray:
    path: get_widget_sample_to_aray
    defaults: 
     _controller: AppBundle:Widget:widget_sample_to_aray
    methods:  GET
    
get_widget_sample_to_slimplate:
    path: get_widget_sample_to_slimplate
    defaults: 
     _controller: AppBundle:Widget:widget_sample_to_slimplate
    methods:  GET
    
get_widget_sample_to_loc:
    path: get_widget_sample_to_loc
    defaults: 
     _controller: AppBundle:Widget:widget_sample_to_loc
    methods:  GET
    
get_widget_sample_to_contrib:
    path: get_widget_sample_to_contrib
    defaults: 
     _controller: AppBundle:Widget:widget_sample_to_contrib
    methods:  GET
    
get_widget_sample_to_doc:
    path: get_widget_sample_to_doc
    defaults: 
     _controller: AppBundle:Widget:widget_sample_to_doc
    methods:  GET
    
get_widget_point_to_contrib:
    path:     /get_widget_point_to_contrib
    defaults: 
     _controller: AppBundle:Widget:widget_point_to_contrib
    methods:  GET